const AboutPage = () => {
  return (
    <div className="w-full py-10 px-6 flex items-center justify-center">
      <div className="bg-card/50 border p-5 w-full max-w-5xl space-y-4">
        <h1 className="text-3xl font-bold">About This Project</h1>
        <p className="text-muted-foreground text-base">
          DaoMath was created by Hailong Dao and Daniel Dao out of a deep
          passion for mathematics and the joy of exploring beautiful ideas. It
          is meant to be a welcoming place where people can share problems,
          exchange insights, and appreciate the creativity that makes math so
          rewarding. Whether it is a clever argument, an interesting example, or
          a question that opens the door to something deeper, this space is
          built around the excitement of learning and discovery.
        </p>

        <p className="text-muted-foreground text-base">
          More than just a collection of problems, DaoMath is a place for
          discussion, curiosity, and having a fun time with math. It is here for
          exploring new perspectives, thinking through challenging ideas with
          others, and enjoying the process of working on something meaningful
          together. The goal is to create a community where conversation feels
          natural, ideas keep moving, and math stays both engaging and alive.
        </p>
        <p className="text-muted-foreground">
          NOTE: GENERATED BY AI. THIS IS A PLACEHOLDER FOR NOW.
        </p>
      </div>
    </div>
  );
};

export default AboutPage;
